apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-slack-assistant
  labels:
    app: ai-slack-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-slack-assistant
  template:
    metadata:
      labels:
        app: ai-slack-assistant
    spec:
      containers:
        - name: ai-slack-assistant
          image: quay.io/vajain/ai-slack-assistant:4.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: ai-slack-assistant-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always