apiVersion: v1
kind: Service
metadata:
  name: ai-slack-assistant
spec:
  selector:
    app: ai-slack-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  # Change to NodePort or LoadBalancer if needed
